version: '3.8'

services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: warefy_db
    environment:
      POSTGRES_USER: warefy
      POSTGRES_PASSWORD: warefy123
      POSTGRES_DB: warefy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warefy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: warefy_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
