[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://warefy-backend.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
